apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "podify.fullname" . }}
  labels:
    {{- include "podify.labels" . | nindent 4 }}
data:
  URL_HOST: {{ .Values.config.podifyURL | quote}}
  STORAGE_DIR: "/storage"
  INITIAL_USER_EMAIL: {{ .Values.config.auth.initialUserEmail | quote }}
  ENABLE_SIGNUP: {{ ternary "yes" "no" .Values.config.signupEnabled | quote }}
