---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "podify.fullname" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{- with .Values.storage.storageClass }}
  storageClassName: {{ . }}
{{- end }}
