apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podify.fullname" . }}
  labels:
    {{- include "podify.labels" . | nindent 4 }}
data:
{{- with .Values.config.auth }}
  SECRET_KEY_BASE: {{ .secretKeyBase | b64enc | quote }}
  INITIAL_USER_PASSWORD: {{ .initialUserPass | b64enc | quote }}
{{- end }}
{{- with .Values.config.postgresql }}
  DATABASE_URL: {{ (printf "%s://%s:%s@%s/%s" "postgres" .user .pass .host .db) | b64enc | quote }}
{{- end }}
{{- with .Values.config.redis }}
  REDIS_URL: {{ (printf "redis%s://%s%s%s/%s" (ternary "s" "" .tls) .user (ternary "" (printf ":%s@" .token) (eq .token "")) .host .db) | b64enc | quote }}
{{- end }}
